FROM python:3.10.18-slim

LABEL description="CogniBrew Catalog Service"
LABEL maintainer="Sukit Supaluckwatjana <sukit.sup@gmail.com>"

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ ./app/
COPY data/ ./data/

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--proxy-headers", "--forwarded-allow-ips=*"]
